name: btyi
channels:
  - conda-forge
  - defaults
dependencies:
  # PYTHON
  - python=3.14.6
  - ipykernel
  - ipywidgets

  # ML ESSENTIALS
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  
  # NLP
  - nltk
  - tiktoken
  - tokenizers
  - spacy       # TODO: Configure GPU Acceleration for this asw
  - sacrebleu
  
  # UI
  - streamlit  
  
  # STUFF THAT DIDNT HAVE GOOD CONDA MIRRORS
  - pip
  - pip:
    # TORCH
    - torch==2.9.0      # v2.9.0 VERY IMPORTANT, newer version dont support my GPU
    - torchtext
    - torchaudio==2.9.0+cu126
    - torchvision
    - --extra-index-url https://download.pytorch.org/whl/cu126

    # NLP
    - wtpsplit
