name: btyi
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.14.6
  - numpy
  - pandas
  - matplotlib
  - scikit-learn
  - scipy
  - pip
  - pip:
    - torch==2.9.0
    - torchtext
    - torchaudio
    - torchvision
    - --extra-index-url https://download.pytorch.org/whl/cu126
  - streamlit