import torch
import math

from typing import Tuple
import src.core.speech.config as conf
from .conformer.subsampler import Subsampler

class LinkNetwork(torch.nn.Module):
    'Takes in the last chunk of outputs from the CTC network and produces contextual embeddings, hopefully refining the hypothesis generated by the CTC net'
    def __init__(self):
        super().__init__()

        self.convs = torch.nn.Sequential(
            torch.nn.Conv1d(
                in_channels=conf.LINK_IN_SIZE,
                out_channels=conf.LINK_SUBSAMPLER_N_FILTERS,
                kernel_size=conf.LINK_SUBSAMPLER_KERNEL_SIZE,
                stride=conf.LINK_SUBSAMPLER_STRIDE,
                padding=conf.LINK_SUBSAMPLER_PAD
            ),
            torch.nn.Conv1d(
                in_channels=conf.LINK_SUBSAMPLER_N_FILTERS,
                out_channels=conf.LINK_SUBSAMPLER_N_FILTERS,
                kernel_size=conf.LINK_SUBSAMPLER_KERNEL_SIZE,
                stride=conf.LINK_SUBSAMPLER_STRIDE,
                padding=conf.LINK_SUBSAMPLER_PAD
            ),
        )

        self.mlp = torch.nn.Sequential(
            torch.nn.Linear(
                in_features=conf.LINK_SUBSAMPLER_N_FILTERS,
                out_features=conf.LINK_H_SIZE
            ),
            torch.nn.SiLU(),
            torch.nn.Linear(
                in_features=conf.LINK_H_SIZE,
                out_features=conf.LINK_OUT_SIZE
            )
        )
    def forward(self, X:torch.Tensor) -> torch.Tensor:
        'Expects (B, T, N_VOCAB+1)'

        X = X.transpose(-1, -2)     # (B, N_VOCAB+1, T)
        subsampled = self.convs(X)   # (B, N_FILTERS, T / 4)
        return self.mlp(subsampled.transpose(-1, -2))        


class PredictionNetwork(torch.nn.Module):
    'For second pass processing of past outputs'
    def __init__(self):
        super().__init__()
        
        self.embedding = torch.nn.Embedding(conf.PRED_IN_RANGE, conf.PRED_EMBEDDING_SIZE)
        self.rnn = torch.nn.LSTM(
            input_size=conf.PRED_EMBEDDING_SIZE,
            hidden_size=conf.PRED_H_SIZE,
            num_layers=conf.PRED_N_LAYERS,
            batch_first=True,
            dropout=conf.PRED_DROPOUT,
            bidirectional=conf.PRED_BIDIRECTIONAL
        )
        self.linear = torch.nn.Linear(
            in_features=conf.PRED_H_SIZE,
            out_features=conf.PRED_OUT_SIZE
        )
        
    def forward(self, X:torch.Tensor, hidden:Tuple|None) -> Tuple[torch.Tensor, Tuple]:
        e = self.embedding(X)
        o, hidden = self.rnn(e, hidden)
        return self.linear(o), hidden
    

class JointNetwork(torch.nn.Module):
    '3 Way Joint Network merging the First Pass CTC Network with the Second Pass Conformer-Transducer architecture'
    def __init__(self):
        super().__init__()

        self.f_project = torch.nn.Linear(conf.CNF_OUT_SIZE, conf.JOINT_OUT_SIZE)
        self.g_project = torch.nn.Linear(conf.PRED_OUT_SIZE, conf.JOINT_OUT_SIZE)
        self.h_project = torch.nn.Linear(conf.LINK_OUT_SIZE, conf.JOINT_OUT_SIZE)

    def forward(
            self,
            f:torch.Tensor,     # Conformer Output
            g:torch.Tensor,     # Prednet Output
            h: torch.Tensor     # Linknet Output
        ) -> Tuple[torch.Tensor, torch.Tensor, torch.Tensor]:
        'Expects shape (B, D)'

        return (
            self.f_project(f),
            self.g_project(g), 
            self.h_project(h)
        )
