import torch
from typing import Tuple
import src.core.speech.config as conf


class LinkNetwork(torch.nn.Module):
    'Takes in the last chunk of outputs from the CTC network and produces contextual embeddings, hopefully refining the hypothesis generated by the CTC net'
    def __init__(self):
        super().__init__()

        self.rnn = torch.nn.LSTM(
            input_size=conf.LINK_IN_SIZE,
            hidden_size=conf.LINK_H_SIZE,
            num_layers=conf.LINK_N_LAYERS,
            batch_first=True,
            dropout=conf.LINK_DROPOUT,
            bidirectional=conf.LINK_BIDIRECTIONAL
        )
        self.linear = torch.nn.Linear(
            in_features=conf.LINK_H_SIZE,
            out_features=conf.LINK_OUT_SIZE
        )

    def forward(self, X:torch.Tensor, hidden:Tuple|None) -> Tuple[torch.Tensor, Tuple]:
        o, hidden = self.rnn(X, hidden)
        return self.linear(o), hidden


class PredictionNetwork(torch.nn.Module):
    'For second pass processing of past outputs'
    def __init__(self):
        super().__init__()
        
        self.embedding = torch.nn.Embedding(conf.PRED_IN_RANGE, conf.PRED_EMBEDDING_SIZE)
        self.rnn = torch.nn.LSTM(
            input_size=conf.PRED_EMBEDDING_SIZE,
            hidden_size=conf.PRED_H_SIZE,
            num_layers=conf.PRED_N_LAYERS,
            batch_first=True,
            dropout=conf.PRED_DROPOUT,
            bidirectional=conf.PRED_BIDIRECTIONAL
        )
        self.linear = torch.nn.Linear(
            in_features=conf.PRED_H_SIZE,
            out_features=conf.PRED_OUT_SIZE
        )
        
    def forward(self, X:torch.Tensor, hidden:Tuple|None) -> Tuple[torch.Tensor, Tuple]:
        e = self.embedding(X)
        o, hidden = self.rnn(e, hidden)
        return self.linear(o), hidden
    

class JointNetwork(torch.nn.Module):
    '3 Way Joint Network merging the First Pass CTC Network with the Second Pass Conformer-Transducer architecture'
    def __init__(self):
        super().__init__()
        
        self.nn = torch.nn.Sequential(
            torch.nn.Linear(
                in_features=conf.JOINT_IN_SIZE,
                out_features=conf.JOINT_H_SIZE,
            ),
            torch.nn.SiLU(),
            torch.nn.Linear(
                in_features=conf.JOINT_H_SIZE,
                out_features=conf.JOINT_OUT_SIZE,
            )
        )

    def forward(self, X:torch.Tensor) -> torch.Tensor:
        return self.nn(X)